### ISSUE TITLE
add monetization to ai2telegramservice.js 

### ISSUE THREAD

**Issue by noxonsu** [noxonsu/Sensorica#1]
сделать бота можно только если ввети лиц код, который чел должен купить по ссылке. на выбор крипта или карты. крипта ведет на товар dash.onout.org , карты ведет на buymeacoffe (позже сделаю линк)

**Comment by Disti4ct** [comment]
Можно доделать интерфейс в даше. Там выбор сделать, через крипту или buymeacoffee.
